- components/common/CommerceHeader.js
- components/common/CommerceLayout.js
- hooks/useInput.js
- pages/index.js
- styles/globals.css
- utils/constants/errors.js
> Chore: indent 수정

- components/common/Footer.js
> Chore: 인덴트 수정

- apis/api-config.js
- apis/defaultApi.js
- pages/test-api.js
Parabole API를 사용하기 위한 기본 API 설정
- api-config 설정 (기본url 및 로컬 구분)
- GET, POST, PATCH, DELETE 기본 API구현
- test-api.js파일을 통해 기본적인 API메소드 호출 방식을 확인해봅시다.
- 기본 API로 호출이 불가능한 메소드는 apis.js에 각자 구현할 수 있도록 합니다.
[#6]
> [Feat:api] 기본 api 함수 개발 및 기본 설정

- apis/api-config.js
- components/common/Pagination.js
- components/product/Product.js
- components/product/ProductList.js
- pages/product/[id].js
- utils/constants/themeColor.js
- utils/moneyUtil.js
상품 목록과 상세페이지 기능 추가
- 화폐단위 util 추가, 테마색 util 추가
- dev 설정 추가 및 변경
- pagination 기능 추가
- 상품 상세페이지 기능 추가
기능 위주로 봐주세용
- 상세페이지
- 페이징
[#4] [#10]
> [Feature/productList] 상품 목록 & 상품 상세페이지

- components/common/Pagination.js
- components/input/Button.js
- components/input/Input.js
- components/product/Product.js
- components/product/ProductList.js
- pages/index.js
- pages/product/[id].js
- pages/store/[id].js
- utils/constants/themeColor.js
- input 컴포넌트들 테마에 맞게 사용성에 맞게 수정
- 상품 상세페이지 구현
- 상품 목록 flex 적용
- input 컴포넌트 수정
input 변경된 대로 다양하게 사용해보시고 동작 안하는거 알려주세요!
사용방법은 pages/product/[id].js 76라인~ 98라인 참고하시고 안되면 언제든 문의주세요
pages/product/[id].js 76라인~ 98라인
카트 추가 및 주문 추가 기능
@IMHYEWON 
input 변경 및 적용된거 확인하고 안되는 부분알려주세요
#4 #10
> [Feature/productDetail] 상품 상세페이지 구현 및 input 아이템 테마적용 및 수정

- components/input/ImageUploader.js
- pages/seller/product/[id].js
ImageUploader에 있는 button을 수정해서 올립니다.
ImageUploader에 있는 Button이 PostButton으로 되어있어서 Button의 smallLineWhite로 변경하여 동작되지 않는 부분을 수정했습니다.
페이지에서 id를 동적으로 받는 부분을 일반 페이지로 받고  id는 따로 sessionStorage에서 가져올 예정입니다.
> [feature/seller_product] ImageUploader에 있는 button 수정

- pages/product/[id].js
상품상세페이지 버튼 error 수정
- 장바구니 버튼 동작 수정
- 바로구매 버튼 동작 수정
> [feature/productDetail] 상품상세페이지  버튼 error 수정

- pages/seller/event/[id].js
- pages/seller/event/list.js
데이터가 없거나 잘못된 요청인 경우 처리 추가
- 리스트 널값 검사
- 삭제 요청시 confirm 팝업
> [Feature/seller-event] 빈값 유효성 검증 및 로직 추가

- components/common/CommerceHeader.js
- pages/user/mypage/index.js
> [feature/mypageMain] mypage 추가

- components/coupon/CouponList.js
- components/event/Event.js
- components/event/EventList.js
- components/event/EventParticipant.js
- components/event/EventParticipantList.js
- components/order/SellerOrder.js
- components/order/UserOrder.js
- pages/seller/coupon/create.js
- pages/seller/coupon/list.js
- pages/seller/event/[id].js
- pages/seller/event/list.js
- pages/seller/product/[id].js
- pages/seller/product/list.js
- pages/user/confirm/[id].js
- pages/user/signin.js
- pages/user/signup.js
- utils/functions.js
판매자가 등록한 상품 목록과 이벤트에 참여한 유저 목록을 판매자가 확인할 수 있다.
+@ PostButton으로 되어있는 부분 수정 및 getTime 함수에 중괄호 걸어놓기
각각의 페이지가 잘 동작하는지 확인하고 GET_DATA가 빠져있는 부분과 PostButton이 있는 부분을 확인하시면 됩니다.
> [feature/seller_list] 목록을 가져오는 기능 구현

- components/order/UserOrder.js
- components/order/UserOrderList.js
- components/product/OrderProductList.js
- pages/user/order/index.js
주문페이지 오류 수정
결제버튼 동작 오류 수정 및 주문페이지 총액 표시 수정
주문페이지에 하나만 불러와지던 오류 수정
> [Feature/orderPay] 주문 오류 수정

- pages/seller/coupon/new.js
Feat, Design: 쿠폰시간은 00:00-23:59로 고정, 디자인 수정
디자인 변경 여뷰
> [feature/coupon] 쿠폰 등록시 시간은 00:00-23:59로 고정, 디자인 수정

- components/coupon/CouponList.js
- components/order/SellerOrderList.js
- components/product/ProductList.js
- components/user/EventApplyList.js
- pages/index.js
- pages/seller/coupon/new.js
- pages/seller/event/[id].js
- pages/seller/product/index.js
- pages/seller/product/list.js
긴급 에러 및 스타일 수정
> 에러 및 스타일 수정
- pages/index.js 상품 전시 갯수 수정
- component/product/ProductList 파일의 Product 컴포넌트 key값 추가
- 쿠폰리스트에서 배정하기 버튼 추가 / 버튼 크기 조정
- pages/seller/coupon/new 문구 수정
- pages/seller/event/[id] 파일의 버튼 색 수정
- component/user/EventApplyList 파일의 userId 수정
- component/order/SellerOrderList 파일의 /orderinfo/seller api로 get 하는 파라미터 수정
- pages/seller/product/index.js 파일의 버튼 색 수정
- pages/seller/product/list 파일의 버튼 색 수정
[https://youtu.be/DR2HIymlnpc](https://youtu.be/DR2HIymlnpc)
> [feature/middle_presentation]Fix: 에러 및 스타일 수정

- components/seller/SellerHeader.js
Hotfix: import useEffect in SellerHeader
> [Hotfix/SellerHeader] Import useEffect in SellerHeader

- components/mypage/UserOrder.js
상품을 누르면 상품화면으로 이동 및 주문일자를 createdAt -> updatedAt으로 변경
> [feature/mypage] 자잘한 수정

- pages/code/google.js
- pages/code/kakao.js
- pages/code/naver.js
- pages/user/signin.js
네이버 카카오 로그인
dev DB 로 로그인이 되는지 확인해주세요 (data 생성 되는지 보세요)
브라우저 localStorage 에 사용자 정보 들어오는지 확인하세요
.env 파일 관리 방법
[#166]
> [feature/login] 네이버 카카오 로그인

- components/product/ProductList.js
- pages/index.js
- pages/product/index.js
- pages/store/[id].js
상품 최신순 정렬 안되던 오류 수정
- 상품 최신순 정렬 안되던 오류 수정
- 모든 상품전시 기본 12개 보이도록 수정
(상품 생성할때 createdAt이 1초 차이나서 뒤죽박죽 되어있는겁니다.)
> [Feature/proeductDesc] 상품 최신순 정렬 안되던 오류 수정

- script/run_dev.sh
특정위치로 보내서 실행하는 과정에서 바로 실행할 수 있도록 수정
``` bash
#!/bin/sh
PROJECT_NAME="The Parabole"
TODAY=$(date +"%Y%m%d")
DEPLOY_PATH=/home/ubuntu
LOG_PATH=$DEPLOY_PATH/log
LINK_LOG_FILE=$LOG_PATH/parabole.log
LOG_FILE=$LOG_PATH/$PROJECT_NAME_$TODAY.log
ERR_LOG_FILE=$LOG_PATH/$PROJECT_NAME_ERROR_$TODAY.log
echo "> Start run.sh for $PROJECT_NAME : $TODAY" >> $LOG_FILE
echo "> Delete log link file" >> $LOG_FILE
rm $LINK_LOG_FILE # 삭제
ln -s $LOG_FILE $LINK_LOG_FILE # 바로가기 파일 생성
echo "> Build log : $LOG_FILE" >> $LOG_FILE 
cd ~/the-parabole-fe
echo "> git pull start" >> $LOG_FILE
git pull -f origin dev
cd submodule
git fetch 
git merge origin main
echo "> Copy .env file" >> $LOG_FILE
cp .env ../.env
echo "> npm install start" >> $LOG_FILE
npm install
npm install -g pm2
echo "> Deploy start "
pm2 reload all …
```
> [Hotfix] sh파일 수정

- pages/seller/event/list.js
- pages/seller/event/new.js
> [feature/auth-event] 인증 부분 수정

- components/product/ProductList.js
> [hotfix/storeinfo] HOTFIX: import 경로 오류 수정

- components/coupon/CouponList.js
- components/coupon/CouponListRadio.js
- components/coupon/UserSearchBar.js
- pages/seller/coupon/new.js
- pages/seller/event/new.js
- pages/signin.js
- pages/signup.js
- utils/constants/errors.js
- 회원가입 입력란 모두 입력 값이 없을 경우 error 처리 (이메일, 비번의 경우 regex 로 validation)
- 로그인 입력란 값이 없을 경우 error 처리 (이메일 형식 regex validation)
- 판매자 쿠폰 목록 & 배정 페이지에 타입 뒤바뀐 것 Fix
- 쿠폰 배정 페이지 사용자 검색창에서 검색된 사용자가 없을 때 오류 해결
- @IMHYEWON 언니가 뼈대 잡아 놓은 error 정의 부분이랑 validation 그대로 사용했어요 도움주셔서 감사합니다.
- notion 오류 기록 페이지에 쿠폰 관련 부분은 전부 수정완료 된거같아서 다른 팀원 돕고 싶은데 제가 필요한 부분 있을까요
작업한 내용의 부분이 잘 반영되었는지 확인 부탁합니다.
> [feature/uifix] 로그인 회원가입 입력창 예외처리 / 쿠폰 입력창 & 노션 오류(잔수정)

- pages/signin.js
> [hotfix/login-password] 로그인 비밀번호 유효성 검사 제거

- apis/defaultApi.js
- pages/product/[id].js
- pages/seller/product/list.js
- pages/seller/product/new.js
- pages/signin.js
- pages/signup.js
- utils/constants/links.js
QA 노션 오류 발견 페이지
3번 판매자 수정 사항들 반영 작업
https://www.notion.so/jungew1509/42b20778dd214e9697d52fed5dddce05
- 판매자 상품 등록 페이지 CSS 적용
- 판매자 상품 등록 페이지 버튼 잘못된 링크 수정 /seller/product_NEW
- 상품 등록 완료된 후 페이지 이동 오류 
- -> 미해결 ( **등록 버튼 한번만 누르세요!!!!!** 
QA 중 발견 : 상품 등록 안된 줄 알고 등록 버튼 두번 누르면 , 이전 사진 물고 상세 사진 4장 들어갑니다. 
이 부분은 구현을 제가 하지 않았기 때문에 페이지 만든 팀원한테 문의 부탁)
`은총`: 상품을 생성한 후 productId를 가져온 후 상품 이미지를 넣는데 페이지가 바뀌지 않는다면 productId가 남아있는 상태로 있어서 기존의 productId에 값이 들어가서 이미지가 중복되는거 같습니당
사진 잘 등록되는지 확인.
화면 디자인 반영 확인 부탁드립니다.
> [feature/sellerfix] 노션 오류 발견 페이지 <테마 3번 판매자 작업>

- components/cart/CartContentDetail.js
- components/cart/CartProduct.js
- components/common/CommerceHeader.js
- components/common/CommerceHeaderMenuModal.js
- components/order/OrderCouponModal.js
- components/order/OrderDetail.js
- components/order/OrderDetailContent.js
- components/order/OrderDetailFooter.js
- components/order/OrderSidebar.js
- components/order/OrdererSection.js
- pages/signin.js
- pages/user/order/index.js
주문 쿠폰적용 알고리즘 변경
- 주문시 쿠폰을 적용하는 알고리즘 수정
- 모바일 화면의 메인 헤더에서 로그인 했을때도 계속 로그인 버튼이 보이는 오류 수정
- 장바구니와 주문 이미지 변형되는 오류 수정
페이지 멈추는지 안멈추는지 확인해주세요...
[#113]
> [Feature/extractCouponOrder] 주문 쿠폰적용 알고리즘 변경

- components/event/EventPrizeContainer.js
- pages/seller/event/new.js
- pages/seller/product/list.js
- utils/constants/types.js
테스트 하면서 발견한 오류를 수정했습니다.
- 이벤트 등록시 날짜 입력값 형식 오류로 등록되지 않는 오류를 수정했습니다.
- 판매자 상품 리스트에서 헤더가 넘어가지 않아 잘못된 상품을 조회하는 오류를 수정했습니다.
- 이벤트 경품 컴포넌트에서 경품 이미지와 경품명이 가운데 정렬되도록 수정했습니다.
> [feature/so] 이벤트 등록 및 기타 오류 수정

- pages/event/[id].js
- pages/seller/event/new.js
> [feature/eventdetail] 충돌 해결 원복

- components/mypage/EventApplyList.js
> [feature/eventWinnerPrize] 이벤트 응모 상품 당첨 내용

- apis/api-config.js
- components/order/SellerOrder.js
- components/order/SellerOrderList.js
- pages/seller/coupon/list.js
- pages/seller/coupon/new.js
- pages/signin.js
- utils/constants/errors.js
- 쿠폰 목록 페이지 제목 레이아웃 수정
- 쿠폰 등록할 때 최대 발행 수량 제한
- 쿠폰 등록할 때 글자 수 제한
- 판매자 주문 내역 페이지 table 디자인 수정
> [fix/errors] QA시 오류 발견 페이지 수정사항

- components/event/EventPrizeContainer.js
- components/event/EventStatusSummary.js
- components/mypage/EventApplyList.js
- pages/event/[id].js
이벤트 응모 화면에서 응모 여부에 따라 버튼 disabled처리 안되는 오류 수정했습니다
마이페이지 이벤트 목록에서 이벤트 두 줄로 안보이던 부분도 함께 수정했습니다
마지막 PR이 되길😭
> [Feature/eventdetails] 이벤트 응모 화면에서 응모 여부에 따라 버튼 disabled처리 안되는 오류 수정

- components/event/EventParticipant.js
- pages/seller/event/[id].js
> [Fix: 이벤트 응모 내역 조회안되는 오류 수정]

- components/cart/CartContentDetail.js
- components/cart/CartContentFooter.js
- components/cart/CartProduct.js
- components/common/MainContent.js
- pages/index.js
> Fix: 메인페이지 파라볼래 문구를 더 파라볼래로 수정

- apis/api-config.js
> [hotfix/url] Frontend 주소 https to http
